server:
  port: ${PORT:8080}

spring:
  application:
    name: VidFlowBackend

  # Servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # MongoDB
  data:
    mongodb:
      auto-index-creation: true

# JWT
auth:
  login:
    path: /api/v2/login
  register:
    path: /api/v2/user/register
  refreshToken:
    path: /api/v2/user/token/refresh
jwt:
  issuer: VidFlow

# Azure
azure:
  cdn:
    baseUrl: ${AZURE_CDN_BASE_URL}
storage:
  connection:
    string: ${AZURE_STORAGE_CONNECTION_STRING}
  blob:
    container:
      name: ${BLOB_CONTAINER_NAME}

# AWS
aws:
  enable: false
  cloud-front:
    baseUrl: ${CLOUD_FRONT_BASE_URL}
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}

spam:
  engine:
    url: ${SPAM_ENGINE_URL}

recommendation:
  engine:
    url: ${RECOMMENDATION_ENGINE_URL}

# Custom
skipUrls: /api/v2/video,/api/v2/video/trending,/api/v2/video/search,/api/v2/video/recommended,/api/v2/video/user/id/{userId},/api/v2/video/id/{videoId},/api/v2/user/id/{userId}/channel
