server:
  port: ${PORT:8080}

spring:
  application:
    name: VidFlowBackend

  # Servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # MongoDB
  data:
    mongodb:
      auto-index-creation: true

# JWT
auth:
  login:
    path: /api/v1/login
  register:
    path: /api/v1/user/register
  refreshToken:
    path: /api/v1/user/token/refresh
jwt:
  issuer: VidFlow

# Azure
azure:
  cdn:
    baseUrl: ${AZURE_CDN_BASE_URL}
storage:
  connection:
    string: ${AZURE_STORAGE_CONNECTION_STRING}
  blob:
    container:
      name: ${BLOB_CONTAINER_NAME}

# AWS
aws:
  enable: false
  cloud-front:
    baseUrl: ${CLOUD_FRONT_BASE_URL}
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}

# Custom
skipUrls: /api/v1/video,/api/v1/video/trending,/api/v1/video/search,/api/v1/video/id/{videoId},/api/v1/video/views/id/{videoId},/api/v1/video/user/id/{userId},/api/v1/user/id/{userId}/channel,/api/v1/user/id/{userId}/subscribers,/api/v1/user/id/{userId}/subscribers/count,/api/v2/video/id/{videoId}
