# MongoDB
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}

# AWS
aws:
  cloud-front:
    base: ${CLOUD_FRONT_BASE}
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}

# JWT
jwt:
  token:
    secret: ${JWT_ACCESS_TOKEN_SECRET}
    expiration: 86400000
  refresh:
    token:
      secret: ${JWT_REFRESH_TOKEN_SECRET}
      expiration: 129600000

logging:
  level:
    com.saransh: debug